# Bad login
POST http://localhost:3001/api/sessions
content-type: application/json

{
    "email": "mario.rossi@gmail.com",
    "password": "wrong_password"
}

###

# Good login
POST http://localhost:3001/api/sessions
content-type: application/json

{
    "email": "andrea.bianchi@gmail.com",
    "password": "password_di_andrea"
}

###

# Logout
DELETE http://localhost:3001/api/sessions/current

###

# Rebuild session
GET http://localhost:3001/api/sessions/current

###

# List courses
GET http://localhost:3001/api/courses

###

# List plan
GET http://localhost:3001/api/plan

###

# Create Plan
POST http://localhost:3001/api/plan
content-type: application/json

{
    "planType": "partTime",
    "courses": [
        "01SQOOV",
        "01TYDOV"
    ]
}

###

# Update Plan
PUT http://localhost:3001/api/plan
content-type: application/json

{
    "planType": "fullTime",
    "courses": [
        "01SQOOV",
        "03UEWOV"
    ]
}

###

# Delete Plan
DELETE http://localhost:3001/api/plan